---
ci:
  autoupdate_branch: main
  skip:
    - markdownlint
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=auto]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: ^\.
      - id: check-added-large-files
        args: ['--maxkb=50000']
      - id: check-case-conflict
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.15.0
    hooks:
      - id: markdownlint
        args: ['--style=.markdown-style.rb', '--no-warnings']
